---
apiVersion: v1
kind: Namespace
metadata:
  name: transmission
  labels:
   app: Torrent
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-Service
spec:
  selector:
    app: Torrent
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Transmission-deployment
  labels:
    app: Torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Torrent
  template:
    metadata:
      labels:
        app: Torrent
    spec:
      containers:
      - name: Torrent
        image: batxif/transmission:latest
        ports:
        - containerPort: 9091
        #livenessProbe:
        #  exec:
        #    command:
        #    - /bin/sh
        #    - -c
        #    - netstat -lntp | grep -q '0.0.0.0:9091'
        #  initialDelaySeconds: 60
        #  periodSeconds: 15
        #  timeoutSeconds: 3
        volumeMounts:
          - name: transmission-conf
            mountPath: /etc/transmission/
          - name: transmission-downloads
            mountPath: /downloads/
      volumes:
        - name: transmission-conf
          hostPath:
            path: /mnt/hdd/conf/transmission/
            type: Directory
        - name: transmission-downloads
          hostPath:
            path: /mnt/hdd/media/
            type: Directory
