---
apiVersion: v1
kind: Service
metadata:
  namespace: trm
  name: trm-svc
spec:
  selector:
    app: torrent
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  type: LoadBalancer
apiVersion: v1
kind: Namespace
metadata:
  name: trm
  labels:
    app: torrent

---
apiVersion: v1
kind: Service
metadata:
  namespace: trm
  name: trm-svc
spec:
  selector:
    app: torrent
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  type: LoadBalancer

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: trm
  name: trm
spec:
  selector:
    matchLabels:
      app: torrent
  replicas: 1
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
      - name: trm
        image: localhost:32767/trm:latest
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - netstat -lntp | grep -q '0.0.0.0:9091'
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 3
        volumeMounts:
          - name: trm-volume
            mountPath: /var/lib/transmission-daemon/info
          - name: trm-descargas
            mountPath: /home/trm
      volumes:
        - name: trm-volume
          hostPath:
            path: /opt/k8s/trm/config
            type: Directory
        - name: trm-descargas
          hostPath:
            path: /mnt/datos/Descargas
            type: Directory
