---

- name: Install dependencies
  apt:
    name: [
      python,
      curl,
      apt-transport-https,
      ca-certificates,
      gnupg2,
      software-properties-common,
    ]
    state: present

- name: add key id
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    filename: docker
    state: present

- name: get docker convenience script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        creates: /home/batxif/get-docker.sh
    - name: install docker
      shell: sh /home/batxif/get-docker.sh
      args:
        creates: /usr/bin/docker

- name: install pip
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: install docker-py and docker-compose
  pip:
    name: [
      docker-py,
      docker-compose,
    ]
    state: present
