---
- name: Instalar dependencias de Docker
  apt:
    name: [
      python,
      curl,
      apt-transport-https,
      ca-certificates,
      gnupg2,
      software-properties-common,
    ]
    state: present

- name: Añadir clave id
  apt_key:
    url: "https://download.docker.com/linux/raspbian/gpg"
    state: present

- name: Añadir repo de docker 
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
   filename: docker
   state: present

- name: Instalar docker 
  apt:
   name: docker-ce
   update_cache: yes
   state: present

- name: Instala pip
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: Instala docker-py y docker-compose
  pip:
    name: [
      docker-py,
      docker-compose,
    ]
    state: present

- name: Habilitar docker
  service: enabled=yes name=docker

- name: Arrancar docker
  service:
    name=docker
    state=restarted