FROM alpine:latest

RUN apk update && apk add --no-cache samba

CMD chmod 0777 /home/

CMD rc-update add samba
CMD rc-service samba start

EXPOSE 137/udp 138/udp 139 445

HEALTHCHECK  CMD netstat -lntp | grep -q '0.0.0.0:445'
