---
apiVersion: v1
kind: Namespace
metadata:
  name: Samba
  labels:
   app: HDD
---
apiVersion: v1
kind: Service
metadata:
  name: Samba-Service
spec:
  selector:
    app: HDD
  ports:
    - name: Samba-prt
      port: 445
      protocol: TCP
      targetPort: 445
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Samba-deployment
  labels:
    app: HDD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HDD
  template:
    metadata:
      labels:
        app: HDD
    spec:
      containers:
      - name: HDD
        image: batxif/samba:latest
        ports:
        - containerPort: 445
        #livenessProbe:
        #  exec:
        #    command:
        #    - /bin/sh
        #    - -c
        #    - netstat -lntp | grep -q '0.0.0.0:9091'
        #  initialDelaySeconds: 60
        #  periodSeconds: 15
        #  timeoutSeconds: 3
        volumeMounts:
          - name: samba-conf
            mountPath: /etc/samba/
          - name: samba-media
            mountPath: /home/
      volumes:
        - name: transmission-conf
          hostPath:
            path: /mnt/hdd/conf/samba/
            type: Directory
        - name: transmission-media
          hostPath:
            path: /mnt/hdd/
            type: Directory
