FROM alpine:latest

RUN apk update && apk add --no-cache transmission-daemon

CMD [ "/usr/bin/transmission-daemon", "-f", "--config-dir", "/var/lib/" ]

EXPOSE 9091/tcp

HEALTHCHECK  CMD curl -f http://localhost:9091/ || exit 1
#alex ->  HEALTHCHECK --interval=15s --timeout=3s --start-period=5s --retries=3 CMD netstat -lntp | grep -q '0.0.0.0:9091'
